FROM jenkins/jenkins:lts
USER root
# create volumes 
RUN mkdir -p /var/jenkins_home
RUN chown -R 1000:1000 /var/jenkins_home/
# create client docker inside jenkins
RUN mkdir -p /tmp/download && \
 curl -L https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz | tar -xz -C /tmp/download && \
 rm -rf /tmp/download/docker/dockerd && \
 mv /tmp/download/docker/docker* /usr/local/bin/ && \
 rm -rf /tmp/download && \
 groupadd -g 999 docker && \
 usermod -aG staff,docker jenkins

USER jenkins